### ISSUE TITLE
date정보 비교기능이 잘못 되었습니다.

### ISSUE THREAD

**Issue by grayroom** [grayroom/SE_Assignment02#35]
<img width="206" alt="image" src="https://github.com/grayroom/SE_Assignment02/assets/43588644/b225bb8f-5930-45c5-8835-f6cf4608a38f">

pointer를 대상으로는 멤버에 대해 화살표로 접근해야 합니다.

**Comment by chlrhkdwls99** [comment]
확인했습니다. 수정하겠습니다.
