### ISSUE TITLE
time정보 비교기능이 잘못 되었습니다.

### ISSUE THREAD

**Issue by grayroom** [grayroom/SE_Assignment02#36]
![image](https://github.com/grayroom/SE_Assignment02/assets/43588644/3110c522-15f5-4702-bb99-3b24cd94de0a)

pointer를 대상으로는 멤버에 대해 화살표로 접근해야 합니다.

**Comment by chlrhkdwls99** [comment]
확인했습니다. 수정하겠습니다.

**Comment by chlrhkdwls99** [comment]
수정한 내역 pr하여, 해결했습니다.
