### ISSUE TITLE
파일정보 조회(filestat2)의 parameter 정의 필요

### ISSUE THREAD

**Issue by grayroom** [grayroom/SE_Assignment02#4]
filestat2의 기능상, 어떤 파일에 대한 정보를 읽어올 것인지 명시해야 할 것으로 보입니다. 저희가 받아와야 할 파일 정보는 아래의 형태입니다.

```c
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <time.h>

struct stat stat2;

//...

void filestat2(/*some args*/)
{
}
``` 
stat2이 전역으로 선언되어있으므로, 다른 함수에서 해당 정보를 받아가기만 하면 됩니다. 하지만 어떤 파일의 정보를 받아올지에 대한 정보를 filestat2의 인자로 결정해아 할 것 같습니다.

**Comment by grayroom** [comment]
@mirusu400 function내부에서 입력 받는 형태로 진행해야 하나요 아니면, string arg를 넘기는 편이 나을까요

**Comment by mirusu400** [comment]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/25397908/235814571-206880c4-40ff-4099-942c-a7725c84612f.png">

`stat1`과 `stat2`가 모두 전역으로 설정되어있으므로 `main`함수에서 두 파일을 열고 각 함수의 리턴타입과 Arg 모두 `void`를 유지하는것이 좋아보입니다

**Comment by grayroom** [comment]
제안서를 더 살펴보니 text1, text2로 명시되어 동일 디렉토리의 해당 파일을 다루도록 구현하겠습니다.

**Comment by grayroom** [comment]
filestat1관련 이슈와 중복이슈로 transfer 하도록 하겠습니다
